# Generated by Django 2.2.5 on 2019-09-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190924_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
    ]
